modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/not-coded/WayFix/issues"
displayURL = "https://modrinth.com/mod/wayfix"
license = "LGPL-2.1"

[[mods]]
modId = "wayfix"
version = "${version}"
displayName = "WayFix"
authors = "NotCoded"
description = "Fixes multiple issues regarding Wayland compatibility for Minecraft."
logoFile = "icon.png"
logoBlur = false

[[dependencies.wayfix]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "${minecraftVersion}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "wayfix.mixins.json"