modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/not-coded/WayFix/issues"
license = "LGPL-2.1"

[[mods]]
modId = "wayfix"
version = "${version}"
displayName = "WayFix"
authors = "NotCoded"
description = "Fixes multiple issues regarding Wayland compatibility for Minecraft."
logoFile = "icon.png"
logoBlur = false

[["dependencies.wayfix"]]
modId = "minecraft"
type = "required"
mandatory = true
versionRange = "${minecraftVersion}"
ordering = "NONE"
side = "CLIENT"

[["dependencies.wayfix"]]
modId = "java"
type = "required"
mandatory = true
versionRange = "[${javaVersion},)"
ordering = "NONE"
side = "CLIENT"

[["dependencies.wayfix"]]
modId = "cloth-config"
type = "required"
mandatory = true
versionRange = "[4.9.0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "wayfix.mixins.json"